### ISSUE TITLE
Pulse audio can work

### ISSUE THREAD

**Issue by metal3d** [dYalib/snips-docker#3]
Hello,
I made a container based on you work (I also point your repository inside the README.md to thank you).

My repository provides a different approach to be able to use "pulseaudio" socket from host to container and avoid the use of satellite. You can check the README file or the `start.sh` script.

Of course, you can apply what I did on your own repository, see here https://github.com/metal3d/docker-snips

One more time, thanks for your work, it helped me a lot to make it working.

PS: I also prefer to use supervisord to startup snips and to not manage logs myself
PS: I'm searching a way to start all the process as "user", the problem is the user id and group id to change to let pulseaudio and container user to be communicate. See my entrypoint that change ids if you're interested.

**Comment by metal3d** [comment]
If I'm not clear, what does my repository is to enable host mic to be use on container, so I can use my container as an assitant - but I didn't made what you did to deploy skills, it's more low level and I use it to "test and develop".

**Comment by metal3d** [comment]
Edit: I now use `fixuid` project that fix id at startup, now everything is working as expected.
This tool is very nice: https://github.com/boxboat/fixuid

**Comment by dYalib** [comment]
Thanks for your comments! Your idea to use the pulseaudio socket from the "docker-host" is great. It makes much sense in an environment without satellites.
To use "supervisord" is one of my future goals, thanks for sharing your solution with me!
I will resume work on the project now, after having had no time in recent weeks.

**Comment by metal3d** [comment]
I'm also very busy :)

It's a pleasure to share that work. No problem
